name: Publish Docker

on:
  release:
    types: [published]

env:
  SUPPORTED_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
  DOCKER_REPO: mortezaprk/kmir

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0

      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPO }}:latest,${{ env.DOCKER_REPO }}:${{ github.event.release.tag_name }}
          platforms: ${{ env.SUPPORTED_PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prepare Release
        run: |
          mkdir -p built
          for platform in ${SUPPORTED_PLATFORMS//,/ }; do
            id=$(docker container create --platform=$platform ${{ env.DOCKER_REPO }}:${{ github.event.release.tag_name }})
            docker cp $id:/kmir built/kmir-${platform//\//-}
            docker rm -v $id
          done

      - name: Upload Release Assets
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          files: built/*

      - name: Update repo description
        uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4.0.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}