name: Publish Docker

on:
  release:
    types: [published]

env:
  SUPPORTED_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
  DOCKER_REPO: mortezaprk/kmir

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPO }}:latest,${{ env.DOCKER_REPO }}:${{ github.event.release.tag_name }}
          platforms: ${{ env.SUPPORTED_PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prepare Release
        run: |
          mkdir -p built
          for platform in ${SUPPORTED_PLATFORMS//,/ }; do
            id=$(docker container create --platform=$platform ${{ env.DOCKER_REPO }}:${{ github.event.release.tag_name }})
            docker cp $id:/kmir built/kmir-${platform//\//-}
            docker rm -v $id
          done

      - name: Upload Release Assets
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: built/*

      - name: Update repo description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}